"""Define immutable default values for visual region verification."""

from visual_verifier.models import DetectionConfig

DEFAULT_DIFF_THRESHOLD_INT = 30
DEFAULT_MIN_BOX_AREA_INT = 80
DEFAULT_MIN_BOX_WIDTH_INT = 6
DEFAULT_MIN_BOX_HEIGHT_INT = 6
DEFAULT_MERGE_KERNEL_SIZE_INT = 9
DEFAULT_BOX_PADDING_INT = 3
DEFAULT_MIN_CHANGED_RATIO_FLOAT = 0.03
DEFAULT_MIN_MEAN_DIFF_FLOAT = 5.0
DEFAULT_MIN_SEVERITY_SCORE_FLOAT = 8.0
DEFAULT_DIFF_NORMALIZER_FLOAT = 80.0
DEFAULT_CHANGED_RATIO_NORMALIZER_FLOAT = 0.75

DEFAULT_DETECTION_CONFIG = DetectionConfig(
    diff_threshold=DEFAULT_DIFF_THRESHOLD_INT,
    min_box_area=DEFAULT_MIN_BOX_AREA_INT,
    min_box_width=DEFAULT_MIN_BOX_WIDTH_INT,
    min_box_height=DEFAULT_MIN_BOX_HEIGHT_INT,
    merge_kernel_size=DEFAULT_MERGE_KERNEL_SIZE_INT,
    box_padding=DEFAULT_BOX_PADDING_INT,
    min_changed_ratio=DEFAULT_MIN_CHANGED_RATIO_FLOAT,
    min_mean_diff=DEFAULT_MIN_MEAN_DIFF_FLOAT,
    min_severity_score=DEFAULT_MIN_SEVERITY_SCORE_FLOAT,
    diff_normalizer=DEFAULT_DIFF_NORMALIZER_FLOAT,
    changed_ratio_normalizer=(DEFAULT_CHANGED_RATIO_NORMALIZER_FLOAT),
)
"""Validated immutable defaults used by public verification calls."""

__all__ = [
    "DEFAULT_BOX_PADDING_INT",
    "DEFAULT_CHANGED_RATIO_NORMALIZER_FLOAT",
    "DEFAULT_DETECTION_CONFIG",
    "DEFAULT_DIFF_NORMALIZER_FLOAT",
    "DEFAULT_DIFF_THRESHOLD_INT",
    "DEFAULT_MERGE_KERNEL_SIZE_INT",
    "DEFAULT_MIN_BOX_AREA_INT",
    "DEFAULT_MIN_BOX_HEIGHT_INT",
    "DEFAULT_MIN_BOX_WIDTH_INT",
    "DEFAULT_MIN_CHANGED_RATIO_FLOAT",
    "DEFAULT_MIN_MEAN_DIFF_FLOAT",
    "DEFAULT_MIN_SEVERITY_SCORE_FLOAT",
]
